import XCTest
import InputReader
import StandardLibraries
import Year2024

class Day8Tests: XCTestCase {
    
    let input = Input("Day8.input", Bundle.module).lines
    let day = Day8()

    func test_part1() {
//        measure {
        XCTAssertEqual(400, day.part1(input))
//        }
    }
    
    func test_part1_example1() {
        let input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".lines
        XCTAssertEqual(14, day.part1(input))
    }
    
    func test_part2() {
//        measure {
        XCTAssertEqual(1280, day.part2(input))
//        }
    }
    
    func test_part2_example1() {
        let input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".lines
        XCTAssertEqual(34, day.part2(input))
    }
}
