import XCTest
import InputReader
import Year2025

class Day7Tests: XCTestCase {
    
    let input = Input("Day7.input", Bundle.module).lines
    let day = Day7()

    func test_part1() throws {
//                measure {
        XCTAssertEqual(1533, day.part1(input))
//                }
    }

    func test_part1_example() throws {
        let input = """
.......S.......
.......^.......
......^.^......
.....^.^.^.....
....^.^...^....
...^.^...^.^...
..^...^.....^..
.^.^.^.^.^...^.
""".lines
        XCTAssertEqual(21, day.part1(input))
    }

    func test_part2() throws {
//                measure {
        XCTAssertEqual(10733529153890, day.part2(input))
//                }
    }

    func test_part2_example() throws {
        let input = """
.......S.......
.......^.......
......^.^......
.....^.^.^.....
....^.^...^....
...^.^...^.^...
..^...^.....^..
.^.^.^.^.^...^.
""".lines
        XCTAssertEqual(40, day.part2(input))
    }
}
/*
 .......S.......
 ...............
 .......1.......1
 ...............
 ......1.1......3
 ...............
 .....1.2.1.....7
 ...............
 ....1.3...1....12
 ...............
 ...1.4...1.1...19
 ...............
 ..1...4.....1..25
 ...............
 .1.1.4.7.0...1.39+1
 ...............
 */
